FROM node:22.12.0-slim

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        bash \
        python3 \
        build-essential \
        git \
        gettext-base \
    && rm -rf /var/lib/apt/lists/*

RUN corepack enable && corepack prepare yarn@1.22.22 --activate

ENV ENKETO_SRC_DIR=/srv/src/enketo
WORKDIR ${ENKETO_SRC_DIR}
