name: 'ci'
run-name: 'Enketo CI'

on:
    push:
    pull_request:
    release:
        types:
            - 'published'

jobs:
  install-build-test:
    uses: ./.github/workflows/install-build-test.yml
